### ISSUE TITLE
Downloading JsonJ from Jitpack.io does not work - any workarounds?

### ISSUE THREAD

**Issue by frjtrifork** [jillesvangurp/jsonj#10]
Are there any other repositories that can be used to fetch json 2.56 from?
I am getting empty results from jitpack.io today (it has been working earlier)

https://jitpack.io/#jillesvangurp/jsonj

I get an empty body for this request

```
curl -kIL https://jitpack.io/#jillesvangurp/jsonj
HTTP/2 200 
date: Fri, 13 Sep 2019 11:46:37 GMT
content-type: text/plain; charset=utf-8
content-length: 0
...stripped the set-cookie
cf-cache-status: HIT
cache-control: private, max-age=86400, stale-if-error=604800
cf-ray: 5159e1b57b213d59-CPH
accept-ranges: bytes
age: 58142
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Fri, 13 Sep 2019 15:37:49 GMT
last-modified: Thu, 12 Sep 2019 15:37:49 EDT
vary: Accept-Encoding
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
server: cloudflare

```

The gradle build exception

```
Could not download jsonj.jar (com.github.jillesvangurp:jsonj:2.56): Skipped due to earlier error
	at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:493)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 33 more
Caused by: org.gradle.internal.resolve.ArtifactResolveException: Could not download jsonj.jar (com.github.jillesvangurp:jsonj:2.56): Skipped due to earlier error
```

The result is that we cannot build our project on any of the cloud CI's as they don't already have jsonj 2.56 cached from back when jitpack.io was working.

**Comment by frjtrifork** [comment]
I think jitpack.io has started using a subdomain in their setup.

In case others get the same error
In your root build.gradle file you must change

```
maven { url 'https://jitpack.io' }
## to
maven { url 'https://javadoc.jitpack.io' }
```

It would be nice if the link to jsonj on jitpack.io in the README here on github could be updated to the new URL - https://javadoc.jitpack.io/#jillesvangurp/jsonj
